// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ProductionPlanWsp.Shared
{
    public partial class VwPlanningProduction
    {
        public string Ctv { get; set; }
        public string Week { get; set; }
        public int? PlanningQuatity { get; set; }
        public string Year { get; set; }
        public int? WeekNumber { get; set; }
        public int? CalculatedTotalWeeklyProduction { get; set; }
        public int? ProductionWeekNo { get; set; }
    }
}