// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ProductionPlanWsp.Shared;

namespace ProductionPlanWsp.Server.Data
{
    public partial class PlanowanieContext : DbContext
    {
        public PlanowanieContext()
        {
        }

        public PlanowanieContext(DbContextOptions<PlanowanieContext> options)
            : base(options)
        {
        }

        public virtual DbSet<VwPlanningProduction> VwPlanningProduction { get; set; }
        public virtual DbSet<VwPoPlanningProduction> VwPoPlanningProduction { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VwPlanningProduction>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VW_Planning_Production");

                entity.Property(e => e.Ctv)
                    .HasColumnName("CTV")
                    .HasMaxLength(50);

                entity.Property(e => e.Week)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.WeekNumber).HasColumnName("Week_number");

                entity.Property(e => e.Year).HasMaxLength(4);
            });

            modelBuilder.Entity<VwPoPlanningProduction>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VW_PO_Planning_Production");

                entity.Property(e => e.Ctv)
                    .HasColumnName("CTV")
                    .HasMaxLength(50);

                entity.Property(e => e.PoQty).HasColumnName("PO_QTY");

                entity.Property(e => e.Week)
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.WeekNumber).HasColumnName("Week_number");

                entity.Property(e => e.Year).HasMaxLength(4);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}